name: Build

on:
    push:
        branches:
            - main

jobs:    
    build:
        runs-on: ubuntu-24.04-arm        
        environment: staging
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install Go 1.24.2
              uses: actions/setup-go@v4
              with:
                go-version: '1.24.2'

            - name: Set up Go modules
              run: go mod tidy

            - name: Build
              run: |
                GOOS=linux GOARCH=arm64 go build -o bootstrap
                zip lambda.zip bootstrap

            - name: Upload to S3
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: "eu-west-2"
              run: |
                aws s3 cp lambda.zip s3://${{ vars.DEPLOYMENT_BUCKET_NAME }}/$(basename ${GITHUB_REPOSITORY}).zip

    deploy:
        runs-on: ubuntu-24.04-arm
        strategy:
            matrix:
                environment: [staging]
        needs: build
        environment: 
            name: staging
        steps:
            - name: Update AWS Lambda
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: "eu-west-2"
              run: |
                aws lambda update-function-code --function-name wordlist-${{ matrix.environment }}-$(basename ${GITHUB_REPOSITORY}) \
                  --s3-bucket ${{ vars.DEPLOYMENT_BUCKET_NAME }} \
                  --s3-key $(basename ${GITHUB_REPOSITORY}).zip
